### ISSUE TITLE
about json_stuff

### ISSUE THREAD

**Issue by lingjiajia** [rhyzomatic/OT.py#1]
I wonder if the coding has a bug? I don't find the parameter "num_messages"  meaningful in the class Bob since no function in the following uses it.

**Comment by wbernoudy** [comment]
Thanks lingjiajia for bringing this up!

This was because I had copied over part of my code from a different repo but not the `json_stuff.py` file. Fixed in 4b135f7ed330c78607e3aa90a4dfb79282114ca9.

You're also right about `num_messages` param for Bob, I've removed that in 68982808b8a3dc58115060d0f7e539f7284e9ece.

May I ask what you're planning to use ot.py for? I mostly created it as a fun exercise. I can definitely put some more work into making the code cleaner, getting rid of the global params, implement a better padding scheme, etc. if that would help.

**Comment by lingjiajia** [comment]
Thinks for replying me. I am a Chinese student. This semester l elected the course cryptography for some special reasons. And the final project is to implement Yao' millionaire problem. This project is too hard for me to finish it. And tomorrow is the deadline. There is not enough time left for me so I planed to search for relevant coding on GitHub. How lazy and stupid I am. I guess I won't pass this course.
